<?php
//	echo $this->form->setAction($this->url());
?>
<div id="page_title">Correct&Contain List</div>
<hr />
<a href=" <?php echo $this->url( array( 'controller' => 'ccitem', 'action' => 'new', )) ?>">New Action item</a>
<br /><br />

<table class="list_table">
	<tr>
		<th class="list_table">Nbr</th>
		<th class="list_table">Id</th>
		<th class="list_table">Description</th>
		<th class="list_table">Owner</th>
		<th class="list_table">Due date</th>
		<th class="list_table">Complete date</th>
	</tr>
	<?php
		$user = new Application_Model_User();
		$userMapper = new Application_Model_UserMapper();
		
		$cnt = 1;
		// do for all action items
		foreach( $this->entries as $entry ) {
	?>

	<tr>
		<td><?php echo $cnt ?></td>
		<td > <?php echo $this->escape( $entry->id ) ?> </td>
		<td > <?php echo $this->escape( $entry->description ) ?> </td>
		<td > <?php
			if ( $userMapper->find( $entry->ownerid, $user ) ) {
				echo $this->escape( $user->getShortname() );
			}
			?>
		</td>
		<td > <?php echo $this->escape( $entry->duedate ) ?> </td>
		<td > <?php	echo $this->escape( $entry->completiondate ) ?>	</td>
		<td>
		<a href="<?php echo $this->url( array( 'controller' => 'ccitem', 'action' => 'update', 'id' => $entry->id )) ?>">details</a>
		</td>
		<td>
		<a href="<?php echo $this->url( array( 'controller' => 'ccitem', 'action' => 'delete', 'id' => $entry->id )) ?>"
			onClick="return confirm('Are you sure you want to delete item number <?php echo $cnt ?> ?') ">
			delete</a>
		</td>

	</tr>
	<?php
	$cnt++;
	} ?>
</table>
<br />
