<?php
//	echo $this->form->setAction($this->url());
?>
<div id="page_title">Attachments</div>
<hr />
<a href=" <?php echo $this->url( array( 'controller' => 'attachment', 'action' => 'upload', )) ?>">Upload file</a>
<br /><br />

<table class="list_table">
	<tr>
		<th class="list_table">Nbr</th>
		<th class="list_table">File name</th>
		<th class="list_table">Size (kB)</th>
		<th class="list_table">Date</th>
	</tr>
	<?php
		$user = new Application_Model_User();
		$userMapper = new Application_Model_UserMapper();

		$cnt = 1;
		// do for all files in the directory
		foreach( $this->files as $file ) {
		
	?>

	<tr>
		<td><?php echo $cnt ?></td>
		<td > <?php echo $file['name'] ?> </td>
		<td > <?php echo $this->escape( ceil((int)$file['size'] / 1024)) ?> </td>
		<td > <?php echo $this->escape( date( 'Y-m-d', $file['time'] )) ?> </td>

		<td>
		<a href="<?php echo $this->url( array( 'controller' => 'attachment' )) ?>">download</a>
		</td>
		<td>
		<a href="<?php echo $this->url( array( 'controller' => 'attachment' )) ?>"
			onClick="return confirm('Are you sure you want to delete file\n<?php echo $file['name'] ?>?') ">
			delete</a>
		</td>

	</tr>
	<?php
	$cnt++;
	} ?>
</table>

<br />
<a href=" <?php echo $this->url( array( 'controller' => 'cat', 'action' => 'update'  )) ?>">Back</a>
<br /><br />
<br />
