<?php
//	echo $this->form->setAction($this->url());
?>
<div id="page_title">NonCompliance List</div>
<hr />
		<a href=" <?php echo $this->url( array( 'controller' => 'nc', 'action' => 'add', )) ?>">New NC</a>
		<br /><br />

<table class="list_table">
	<tr>
		<th class="list_table">Id</th>
		<th class="list_table">Raised by</th>
		<th class="list_table">Date raised</th>
		<th class="list_table">Status</th>
		<th class="list_table">Assigned to</th>
	</tr>
	<?php 
		$user = new Application_Model_User();
		$userMapper = new Application_Model_UserMapper();
		foreach( $this->entries as $entry ) { 2
	?>

	<tr>
		<td > <?php echo $this->escape( $entry->id ) ?> </td>
		<td > <?php
			$userMapper->find( $entry->initiatorid, $user );
			echo $this->escape( $user->getShortname() );
			?>
		</td>
		<td > <?php echo $this->escape( $entry->initdate ) ?> </td>
		<td > <?php
			$values = Zend_Registry::get('status');
			echo $this->escape( $values[ $entry->getStatusid() ] );
			Zend_Debug::dump( $entry);
			?>
		</td>
		<td> <?php
			// assigned to can be empty
			if ($userMapper->find( $entry->focalid, $user ) )
				echo $this->escape( $user->getShortname() );
			?>
		</td>
		<td style="padding: 2px 10px 0px 10px">
		<a href="<?php echo $this->url( array( 'controller' => 'nc', 'action' => 'update', 'id' => $entry->id )) ?>">details</a>
		</td>
	</tr>
	<?php } ?>
</table>
<br />
