<?php $this->placeholder('sidebar')->captureStart() ?>
<h4>Cats admin</h4>

<?php 
	$cat = new Zend_Session_Namespace('cat');
	$nc = $this->getCurrentNc();
	if ( ! isset ($nc)) {
		echo "No NC selected";
		return;
	}

	$filter = new Zend_Session_Namespace('filter');
	$filterType = $filter->type;
	?>
<fieldset>
	<legend>NC info</legend>
<table>
	<tr>
		<td>NC id</td>
		<td style="background-color: lightgray;border:1px black solid"><?php echo $nc->getId() ?></td>
	</tr>
	<tr>
		<td>Status</td>
		<td style="background-color: lightgray; border:1px black solid"><?php echo $this->getStatusDescription( $nc->getStatusid() ) ?></td>
	</tr>
	<tr>
		<td colspan="2">Summary</td>
	</tr>
	<tr>
		<td colspan="2" style="background-color: lightgray; border:1px black solid"><?php echo $nc->getSummary() ?></td>
	</tr>
</table>
</fieldset>

<?php $this->placeholder('sidebar')->captureEnd() ?>