<?php $this->placeholder('sidebar')->captureStart() ?>
<h4>Cats admin</h4>

<?php 
	$cat = new Zend_Session_Namespace('cat');
	$nc = $this->getCurrentNc();
	if ( isset ($nc)) {
		echo "Selected NonCompliance<br />";
		echo "id: ".$nc->getId()."<br/>";
		echo "summary: <br/>".$nc->getSummary();
	} else
		echo "No NonCompl selected";
	echo "<br /><br />";
	?>

<?php $this->placeholder('sidebar')->captureEnd() ?>