<?php $this->placeholder('sidebar')->captureStart() ?>
<h4>Cats admin</h4>

<fieldset>
	<legend>NC info</legend>

<table>

<?php
	$cat = new Zend_Session_Namespace('cat');
	$nc = $this->getCurrentNc();
	if ( ! isset ($nc)) {
		echo "<tr><td>";
		echo "no NC selected";
		echo "</td></tr>";
	} else {
	?>
	<tr>
		<td>NC id</td>
		<td style="background-color: lightgray;border:1px black solid"><?php echo $nc->getId() ?></td>
	</tr>
	<tr>
		<td>Status</td>
		<td style="background-color: lightgray; border:1px black solid"><?php echo $this->getStatusDescription( $nc->getStatusid() ) ?></td>
	</tr>
	<tr>
		<td colspan="2">Summary</td>
	</tr>
	<tr>
		<td colspan="2" style="background-color: lightgray; border:1px black solid"><?php echo $nc->getSummary() ?></td>
	</tr>
	<?php
	}
	?>
</table>
</fieldset>

<?php $this->placeholder('sidebar')->captureEnd() ?>