<?php
//	echo $this->form->setAction($this->url());
?>
<div id="page_title">List</div>
<hr />
		<a href=" <?php echo $this->url( array( 'controller' => 'cat', 'action' => 'add', )) ?>">New NC</a>
		<br /><br />

<table class="list_table">
	<tr>
		<th class="list_table">Id</th>
		<th class="list_table">Raised by</th>
		<th class="list_table">Date raised</th>
		<th class="list_table">Status</th>
		<th class="list_table">Assigned to</th>
	</tr>
	<?php 
		$user = new Application_Model_User();
		$userMapper = new Application_Model_UserMapper();
		foreach( $this->entries as $entry ) { 
	?>

	<tr>
		<td > <?php echo $this->escape( $entry->id ) ?> </td>
		<td > <?php
				$userMapper->find( $entry->initiatorid, $user );
				echo $this->escape( $user->getShortname() );
				?> </td>
		<td > <?php echo $this->escape( $entry->initdate ) ?> </td>
		<td > <?php echo $this->escape( $entry->statusid ) ?> </td>
		<td > <?php
				$userMapper->find( $entry->focalid, $user );
				echo $this->escape( $user->getShortname() );
				?> </td>

		<td style="padding: 2px 10px 0px 10px">
		<a href=" <?php echo $this->url( array( 'controller' => 'cat', 'action' => 'update', 'id' => $entry->id )) ?>">details</a>
		</td>
	</tr>
	<?php } ?>
</table>
<br />
