<?php
//	echo $this->form->setAction($this->url());
?>
<div id="page_title">Non compliance</div>
<hr />
<table class="list_table">
	<tr>
		<th class="list_table">Id</th>
		<th class="list_table">Raised by</th>
		<th class="list_table">Date raised</th>
		<th class="list_table">Status</th>
		<th class="list_table">Assigned to</th>
	</tr>
	<?php foreach( $this->entries as $entry ) { ?>
	<tr>
		<td > <?php echo $this->escape( $entry->id ) ?> </td>
		<td > <?php echo $this->escape( $entry->initiatorid ) ?> </td>
		<td > <?php echo $this->escape( $entry->initdate ) ?> </td>
		<td > <?php echo $this->escape( $entry->statusid ) ?> </td>
		<td > <?php echo $this->escape( $entry->focalid ) ?> </td>
		<td style="padding: 2px 10px 0px 10px">
		<a href=" <?php echo $this->url( array( 'controller' => 'cat', 'action' => 'update', 'id' => $entry->id )) ?>">details</a>
		</td>
	</tr>
	<?php } ?>
</table>
<br />
