<?php

// ensure user is logged in
$auth = Zend_Auth::getInstance();
if ( ! $auth->hasIdentity()) {
	echo 'You must be logged in to access this page';
	return;
} else {
	$userId = $auth->getIdentity()->id;
}
?>

<div id="page_title">NonCompliance List</div>
<hr />
		<a href=" <?php echo $this->url( array( 'controller' => 'cat', 'action' => 'add', )) ?>">New NC</a>
		<br /><br />
<?php
		if ( ! $this->entries ) {
			echo "No entries found";
			return;
		}
?>
<table class="list_table">
	<tr>
		<th class="list_table">Id</th>
		<th class="list_table">Raised by</th>
		<th class="list_table">Date raised</th>
		<th class="list_table">Status</th>
		<th class="list_table">Assigned to</th>
	</tr>
	<?php 
		$user = new Application_Model_User();
		$userMapper = new Application_Model_UserMapper();

		foreach( $this->entries as $entry ) { 
	?>

	<tr>
		<td > <?php echo $this->escape( $entry->id ) ?> </td>
		<td > <?php
			$userMapper->find( $entry->initiatorid, $user );
			echo $this->escape( $user->getShortname() );
			?>
		</td>
		<td > <?php echo $this->escape( $entry->initdate ) ?> </td>
		<td > <?php
			$values = Zend_Registry::get('status');
			echo $this->escape( $values[ $entry->statusid ] );
			?>
		</td>
		<td> <?php
			// assigned to can be empty
			if ($userMapper->find( $entry->focalid, $user ) )
				echo $this->escape( $user->getShortname() );
			?>
		</td>
		<td style="padding: 2px 10px 0px 10px">
		<a href="<?php echo $this->url( array( 'controller' => 'cat', 'action' => 'update', 'id' => $entry->id )) ?>">details</a>
		</td>
	</tr>
	<?php } ?>
</table>
<br />
