<div id="page_title">NonCompliance Details</div>
<hr />
<?php
//check access

// ensure user is logged in

$user = $this->getCurrentUser();
if ( ! $user ) {
	echo 'You must be logged in to access this page';
	return;
}
//ensure an nc is selected
$nc = $this->getCurrentNc();
if ( ! $nc ) {
	echo 'An NC must be selected before accessing this page';
	return;
}

// if status is 'NC_Submitted then we can have two situations:
// awaiting approval or when you are the focal then 'please approve'
if ( array_search( $nc->getStatusid(), Zend_Registry::get( 'status') ) == 'NC_Submitted' ) {
	if ( $user->getId() == $nc->getFocalid() ) {
		echo "Awaiting your approval: ";
		?>
		<a href="<?php echo $this->url( array( 'controller'=>'cat', 'action'=>'approve', 'id'=> $nc->getId() )) ?>" ><input type="button" value="Approve"></a>
		<?php
//		$this->view->_helper->flashMessenger->addMessage(array('successMsg'=>'Awaiting approval of focal'));
	} else {
//		$this->_helper->flashMessenger->addMessage(array('successMsg'=>'Awaiting your approval'));
		echo "Awaiting approval by Focal";
	}
	echo "<hr />";
}

// show form
echo $this->form->setAction($this->url());
?>
<!-- // add 'attchements' button -->
<a href="<?php echo $this->url( array( 'controller'=>'attachment', 'action'=>'index', 'id'=> $nc->getId() )) ?>" ><input type="button" value="Attachments"></a><br /><br />

