<!-- application/layouts/scripts/layout.phtml -->
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Zend Framework Quickstart Application</title>
  <?php echo $this->headLink()->appendStylesheet('/css/global.css') ?>
  <?php
//  if ( $this->dojo()->isEnabled() ) {
//	  $this->dojo()->setLocalPath( $this->baseUrl() . '/scripts/dojo/dojo/dojo.js');
//	  $this->dojo()->addStyleSheetModule('scripts.dojo.dijit.themes.tundra');
//					->addLayer($this->baseUrl() . '/scripts/dojo/dojo/dojo.js');
//	  echo $this->dojo();
//  }
?>
</head>
<body class="tundra">
<table id="basic" width="100%">
	<tr><td>
	<table width="100%">
		<tr id="first_line">
		<?php echo $this->render( 'firstline.phtml'); ?>
		</tr>
		<tr id="header">
		<?php echo $this->render( 'logo.phtml'); ?>
		</tr>
	</table></td></tr>
	<tr><td><table width="100%">
		<tr>
			<td id="left_menu" width="150px" rowspan="2">
				<?php echo $this->placeholder('sidebar') ?>
			</td>
			<td id="top_menu">
				<?php echo $this->placeholder('topmenu') ?>
			</td>
		</tr>
		<tr>
			<td id="content">
			<!-- // any messages -->
			<?php echo $this->flashMessages();  ?>
			
			<?php echo $this->layout()->content ?>
			</td>
		</tr>
		<tr id="footer" >
		<?php echo $this->render('footer.phtml')?>
	
		</tr>
    </table>
	</td></tr>
</table>
</body>
</html>