<!-- application/layouts/scripts/layout.phtml -->
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Zend Framework Quickstart Application</title>
  <?php echo $this->headLink()->appendStylesheet('/css/global.css') ?>
</head>
<body>
<table id="basic" width="100%">
	<tr><td>
	<table width="100%">
		<tr id="first_line">
			<td colspan="2" id="first_line">
				<ul>
					<li><a href="<?php echo $this->url(
							array( 'controller' => 'index', ),
							'default', true) ?>">Home</a>
					</li>
					<li>|</li>
					<li><a href="<?php echo $this->url(
							array( 'controller' => 'cat', ),
							'default', true) ?>">Cats</a>
					</li>
					<li>|</li>
					<li><a href="<?php echo $this->url(
							array( 'controller' => 'user', ),
							'default', true) ?>">User admin</a>
					</li>
					<li>|</li>
					<li><a href="<?php echo $this->url(
							array( 'controller' => 'settings', ),
							'default', true) ?>">Settings</a>
					</li>
				</ul>
				<ul style="float:right">
					<li><?php echo $this->loggedInAs(); ?> </li>
				</ul>
			</td>
		</tr>
		<tr id="header">
			<td colspan="2">
				<div id="main_logo">RQTS</div>
			</td>
		</tr>
	</table></td></tr>
	<tr><td><table width="100%">
		<tr>
			<td id="left_menu" width="150px" rowspan="2">
				<?php echo $this->placeholder('sidebar') ?>
			</td>
			<td id="top_menu">
				<?php echo $this->placeholder('topmenu') ?>
			</td>
		</tr>
		<tr>
			<td id="content">
			<?php echo $this->layout()->content ?>
			</td>
		</tr>
		<tr id="footer" >
			<td></td>
			<td id="footer">advance your standards - rqts &copy; 2011</td>
		</tr>
    </table>
	</td></tr>
</table>
</body>
</html>