<p><a href="<?php echo $this->url(
    array(
        'controller' => '',
        'action'     => 'index'
    ),
    'default',
    true) ?>">Sign Our Guestbook</a></p>

User Entries: <br />
<dl>
    <?php foreach ($this->entries as $entry): ?>
    <dt><?php echo $this->escape($entry->nickname) ?></dt>
    <dd><?php echo $this->escape($entry->firstname) ?></dd>
    <dd><?php echo $this->escape($entry->lastname) ?></dd>
    <?php endforeach ?>
</dl>